rss-streaming-service:
  rss-service-mode: streaming
  rss-sources:
  - https://www.nasa.gov/rss/dyn/breaking_news.rss
  - https://www.nasa.gov/rss/dyn/educationnews.rss

logging.level.org.springframework.web: DEBUG
